### PR TITLE
Set EXPIRE on redis keys

### PR DESCRIPTION
**Pull request by osahyoun**

### CODE REVIEW

**Comment by osahyoun** [comment]
@rodrei have set expiration time to 10 minutes for both stores. Is this enough time?

**Comment by osahyoun** [comment]
@rodrei https://github.com/SumOfUs/champaign-ak-processor/pull/103/commits/e5612b152621ae8ecbbe7e6d9dba250e39295b2c

Please merge if you're happy

**Comment by rodrei** [comment]
@osahyoun for Campaigns we shouldn't expire. Memory is not an issue here, this is a feature that's not used very much, and means only one new record per group of pages that use it, so no big deal when it comes to memory.

For Actions I'd be more lenient since we can have surveys that are quite long and require more than 10 min to fill. What about 30 min or 1 hr?

**Comment by osahyoun** [comment]
Hi @rodrei is this the same comment from last time? I'm confused!

**Comment by rodrei** [comment]
Yeah, this was what I suggested last time

**Comment by rodrei** [comment]
hey @osahyoun, sorry for the confusion!

Code looks good! I see you're setting a 24hs as the expiration time, IMO 1hr is enough but a full day wont be an issue either. 👍  to merge!

**Comment by osahyoun** [comment]
Thanks, @rodrei

**Pull request merged**
