### PR TITLE
Release

### PR DESCRIPTION
**Pull request by osahyoun**
Campaign management feature

### CODE REVIEW

**Comment by osahyoun** [comment]
@rodrei @NealJMD before merging, can you confirm that all parts of the worker have been tested on staging. 

Testing checklist:
- [ ] Action creation
- [ ] Page creation
- [ ] Page updating
- [ ] Campaign creation
- [ ] Campaign updating

**Comment by paulaferris** [comment]
I hadn't tested this on staging so was having a look now. I'm managing to create pages and campaigns, and update names. However, I'm encountering bugs on multilingual campaign association. Each time I've created a page and associated with a multilingual campaign, the association hasn't been passed to ActionKit. It has, but only after playing around with the page more (changing language, for example, and resaving). Not quite sure what exactly has tripped the association to be correctly passed, but hasn't worked on the first time. For example:

screen shot 2016-08-18 at 11 35 37 am
screen shot 2016-08-18 at 11 35 25 am

This is on staging on the following page: https://action-staging.sumofus.org/a/paul-test-campaign-3

**Comment by rodrei** [comment]
@paulaferris Yes, you're right! The problem is that the auto-saving is not working! Reviewing this now.

**Comment by rodrei** [comment]
@paulaferris this has already been fixed on staging.

**Comment by rodrei** [comment]
@paulaferris Sorry, I misunderstood your bug report, thought campaign info was not being saved in Champaign, and you were referring to AK.  Just spotted the issue, and made a PR on the Champaign project to address it: https://github.com/SumOfUs/Champaign/pull/632

So, @osahyoun I think we're good to deploy this.

**Comment by osahyoun** [comment]
💯

**Pull request merged**
