### PR TITLE
Sending a response for SQs.

### PR DESCRIPTION
**Pull request by EricBoersma**

### CODE REVIEW

**Comment by Tuuleh** [comment]
I deployed this, it works well if messages get process alright. Just wondering - is there any occasion where we'd hit this and send 200 if the message doesn't get processed all right? Sending back 200 tells the daemon to delete the message, so a message that wasn't processed right would be lost.

**Comment by EricBoersma** [comment]
Yeah, there’s a small subset of situations where a page couldn’t be saved (we ignore failed actions because there’s basically nothing we can do to get a user to retry an action in the time window necessary) on ActionKit - for example, you chose a name that couldn’t be saved in ActionKit. In that case, the original SQS message is valid, so we send back a 200, but we log AK’s error on the offending page and set its status to failed, which we’ll need to highlight in the UI.

-- 
Eric Boersma
Director of Engineering, SumOfUs
616-403-9209 (Grand Rapids, MI)
Skype: eric_sou

On September 1, 2015 at 2:40:24 PM, Tuuli Pöllänen (notifications@github.com) wrote:

I deployed this, it works well if messages get process alright. Just wondering - is there any occasion where we'd hit this and send 200 if the message doesn't get processed all right? Sending back 200 tells the daemon to delete the message, so a message that wasn't processed right would be lost.

**Comment by Tuuleh** [comment]
Something in the lines of that the page has been saved, but is inactive
because it does not have a corresponding ActionKit page because of error x
in field y?

**Comment by EricBoersma** [comment]
Basically, yes. It doesn't set the page to inactive, though it probably could. It does set the page's `status` to failed, and lists the errors that came back from the AK API into the `messages` field.

**Comment by Tuuleh** [comment]
I think it'd make sense that the page would be set to inactive, because
actions taken on it would not be recorded to AK.

**Pull request merged**
